language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm
    - nightly

branches:
    only:
        - master
        - /^\d+\.\d+\.\d+$/

matrix:
    fast_finish: true
    include:
        - php: 5.5
          env: SYMFONY_VERSION=2.3.* DB=mysql
        - php: 5.5
          env: SYMFONY_VERSION=2.4.* DB=mysql
        - php: 5.5
          env: SYMFONY_VERSION=2.5.* DB=mysql
        - php: 5.5
          env: SYMFONY_VERSION=2.6.* DB=mysql
        - php: 5.5
          env: SYMFONY_VERSION=2.7.* DB=mysql
        - php: 5.5
          env: SYMFONY_VERSION=2.8.*@dev DB=mysql
    allow_failures:
        - php: nightly

before_script:
    # Dependencies
    - composer self-update
    - composer install
    - ls
    - ls app
    - ls app/config
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

    # Database
    - cp Tests/Mock/app/config/parameters.yml app/config/parameters.yml
    - php app/console doctrine:database:create
    - php app/console doctrine:schema:create

    # Bundle
    - php app/console generate:bundle --namespace InspiredBeings/TestBundle --bundle-name=TestBundle --dir=src --format=yml --no-interaction

    # Form Model
    - mkdir src/InspiredBeings/TestBundle/Form
    - mkdir src/InspiredBeings/TestBundle/Form/Model
    - cp Tests/Mock/src/InspiredBeings/TestBundle/Form/Model/StudentApplication.yml src/InspiredBeings/TestBundle/Form/Model/StudentApplication.yml

script: phpunit -c app

notifications:
    email: ivan.gabriele@gmail.com
